### ISSUE TITLE
importlib.metadata.PackageNotFoundError: wger

### ISSUE THREAD

**Issue by RlndVt** [wger-project/docker#16]
Hello,

I can't get your example working, I get the following error in the web docker-compose logs:

```
web_1         | Waiting for postgres...
web_1         | PostgreSQL started :)
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/bin/wger", line 33, in <module>
web_1         |     sys.exit(load_entry_point('wger', 'console_scripts', 'wger')())
web_1         |   File "/usr/bin/wger", line 22, in importlib_load_entry_point
web_1         |     for entry_point in distribution(dist_name).entry_points
web_1         |   File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
web_1         |     return Distribution.from_name(distribution_name)
web_1         |   File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
web_1         |     raise PackageNotFoundError(name)
web_1         | importlib.metadata.PackageNotFoundError: wger
web_1         | Running in production mode, running collectstatic now
```

Thanks for looking into this, sorry that I don't have anything else to add.

**Comment by rolandgeider** [comment]
Should be fixed now. I still have no idea why it stopped working

**Comment by RlndVt** [comment]
Thank you, just tested and works.

**Comment by DrNion** [comment]
Sadly I still have the very same problem :(
(and the same logs with the same lines etc)
I used Wger for more than a year without any problems... so ty for that btw ;)

**Comment by rolandgeider** [comment]
Are you also using the docker version @DrNion ?

**Comment by DrNion** [comment]
Yes
